name: banano-reddit-tipbot
channels:
  - defaults
dependencies:
  - python=3.7
  - pandas=0.25
  - requests
  - pip
  - pip:
      - praw==6.4.0
      - qrcode==6.1
      - click
      - black
      - pytest
      - peewee
      - pymysql
      - psycopg2-binary

